INSERT INTO users (name, email) VALUES
('Adam Elhassan', 'adam.elhassan@gmail.com'),
('Sara Benali', 'sara.benali@gmail.com'),
('Youssef Amrani', 'youssef.amrani@gmail.com'),
('Lina Oukacha', 'lina.oukacha@gmail.com'),
('Omar Tahiri', 'omar.tahiri@gmail.com'),
('Khadija Mansouri', 'khadija.mansouri@gmail.com'),
('Anas Bouzid', 'anas.bouzid@gmail.com'),
('Imane Chafik', 'imane.chafik@gmail.com'),
('Hamza Rahmani', 'hamza.rahmani@gmail.com'),
('Nour Eddine Ait', 'noureddine.ait@gmail.com'),
('Ayoub Fassi', 'ayoub.fassi@gmail.com'),
('Salma Idrissi', 'salma.idrissi@gmail.com'),
('Mehdi Berrada', 'mehdi.berrada@gmail.com'),
('Hajar Kabbaj', 'hajar.kabbaj@gmail.com'),
('Ismail Ziani', 'ismail.ziani@gmail.com'),
('Fatima Zahra Belkadi', 'fatimazahra.belkadi@gmail.com'),
('Rachid El Amrani', 'rachid.elamrani@gmail.com'),
('Zineb Ouahbi', 'zineb.ouahbi@gmail.com'),
('Soufiane Lahlou', 'soufiane.lahlou@gmail.com'),
('Meryem Skalli', 'meryem.skalli@gmail.com');
